title: İn Silico Pharmacy
description: Hesaplamalı Kimya ve Biyoloji ile ilgili bir website
lang: tr
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# (İsteğe bağlı) Sosyal linkler
github:
  is_project_page: true
  repository_url: https://github.com/aguveli53/insilicopharmacy
